### ISSUE TITLE
Update the record show page

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1050]
See [the interactive prototype](https://www.figma.com/proto/nkgg905s5FyXoyPZjVMco0/EarthWorks?page-id=0%3A1&node-id=911-24473&viewport=-7294%2C1192%2C0.56&t=kYki5n8Z1jZKPmeu-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=911%3A24473&show-proto-sidebar=1).

- [x] #673
- [x] #646
- [x] #1187
- [x] #1137
- [x] Question about where static map should go in designs -- might need an additional design
- [x] Code snippets samples link (#1049)
- [x] https://github.com/sul-dlss/earthworks/issues/646
- [x] #1159

**Comment by dbranchini** [comment]
Other things to note:

- Map is grayscale (or the same one used in Harvard's GeoBL instance - https://hgl.harvard.edu/)
- "Also listed in" (links to SDR and SearchWorks) and "Item belongs to a collection" are considered additional context and they are in a separate panel in the sidebar below the download options. We should consider removing the 
- Citation should reference PURL (Available at [URL]) and not EarthWorks link (Retrieved from [URL]) since PURL is the permanent/persistant location. 
- Preview of attributes table (data records)
- Alert for maps that are not georeferenced

For various types of records, see each of the following:

- Stanford data public - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=911-24473&t=fJ7frFCTY19oqToM-4
- Stanford data restricted - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=1123-15014&t=fJ7frFCTY19oqToM-4
- Other institution public - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=911-24153&t=fJ7frFCTY19oqToM-4
- Other institution restricted - decided to not include these records since there's no way for a user to obtain them
- Map not georeferenced - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=911-24247&t=fJ7frFCTY19oqToM-4
- Map georeferenced - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=942-31562&t=fJ7frFCTY19oqToM-4

For various breakpoints/viewports:

Small desktop view - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=232-5422&t=fJ7frFCTY19oqToM-4
Tablet view - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=228-8072&t=fJ7frFCTY19oqToM-4
Phone view - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=228-8077&t=fJ7frFCTY19oqToM-4

**Comment by marlo-longley** [comment]
We will discuss splitting up this ticket at a team meeting.

**Comment by marlo-longley** [comment]
- [ ] attribute table preview only
- [ ] restricted dataset -- 
- [ ] item belongs to collection sidebar area -- more complex situations with relationships and labelling? complex example: https://earthworks.stanford.edu/catalog/p16022coll205:265
- [ ] Map is not georeferenced info box 
- [ ] Question about where static map should go in designs -- might need an additional design
- [ ] Click to wake map
- [ ] Loading indication for large download clicks? -- "Download ready" or Toast?
- [ ] Responsive views: wrapping, stacking (map below)
- [ ] Grayscale map: Concern about conflict between sul-embed map.
