### ISSUE TITLE
Update the search results page

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1052]
See [the interactive prototype](https://www.figma.com/proto/nkgg905s5FyXoyPZjVMco0/EarthWorks?page-id=0%3A1&node-id=9-148&viewport=-3973%2C-836%2C0.58&t=5oPw70wWwebL9uPW-1&scaling=min-zoom&starting-point-node-id=9%3A148&show-proto-sidebar=1).

May need splitting into separate tickets.

Note that the suggestion feature for the search bar is separate: #1047.

---
Overall -- check to see if VCs exist in Blacklight first.
Also note that Figma designs contain multiple breakpoints / screen sizes.

- [x] #1171
- [x] #1185
- [x] #1143
- [x] #1135
- [x] #1198
- [x] #1133
- [x] #1170

**Comment by dbranchini** [comment]
One note - let's default to 20 per page. It looks like Blacklight defaults are 10, 20, 50 and 100, and those options are fine.

**Comment by dnoneill** [comment]
Map is now sticky with closing of https://github.com/geoblacklight/geoblacklight/issues/1273

**Comment by dbranchini** [comment]
A few links to designs in Figma, including designs at various breakpoints/viewport sizes:

Bootstrap XXL (includes a 16in laptop) - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=540-34279&t=fJ7frFCTY19oqToM-4

Small desktop/laptop - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=331-11157&t=fJ7frFCTY19oqToM-4 

Tablet - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=335-13892&t=fJ7frFCTY19oqToM-4 (note there's no map)

Phone - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=335-15305&t=fJ7frFCTY19oqToM-4 (note there's no map)

**Comment by marlo-longley** [comment]
We will discuss splitting up this ticket at a team meeting.

**Comment by marlo-longley** [comment]
Overall -- check to see if VCs exist in Blacklight first.

- [ ] Previous/next and Sort/Per Page is a VC in Blacklight (20 per page etc.), Expanded/Compact view
- [ ] Facets and Facet indicators with x's at top of view. Facets are correct in Figma design (except for duplicate Year).
- [ ] Year facet redesign: remove histogram due to accessibility. Design still in progress.
- [ ] Consider renaming Resource Class/Type. Lower priority breakout task.
- [ ] Title hover with Map bounding box
- [ ] Bookmark (Niqui has already done work?)
- [ ]
