### ISSUE TITLE
Replace Clover viewer with Mirador viewer

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1112]
I hastily added [some JS](https://github.com/sul-dlss/earthworks/blob/main/app/assets/javascripts/modules/mirador.js) during the GBL v4 upgrade so that we would use Mirador instead of Clover as the viewer for IIIF content – this way things would appear more consistent for Earthworks patrons, since anything using sul-embed for IIIF will be using mirador already.

We need to:
- update this JS to become a stimulus controller, modeled after the viewer controllers in geoblacklight 
- make sure that it works for both IIIF manifest items and IIIF single-image items (see the clover viewer controller in GBL for how to do this)

**Comment by thatbudakguy** [comment]
Probably related to/fixes #1106

**Comment by marlo-longley** [comment]
Having issues importing Mirador 3. I think the reason is that GBL has React 18 as a dependency, yet Mirador 3 is incompatible with React 18. There may be some complex stuff going on with importmaps and these dependencies of Mirador; alternatively Mirador 3 may be releasing an ES build that is hard to work with.

Possibly we can do this ticket when Mirador 4 is released. 

Closing for now; will push up my work setting this up to a branch. We will continue to use Clover despite the visual inconsistency.

**Comment by marlo-longley** [comment]
Here is the branch where I'm archiving my work:
https://github.com/sul-dlss/earthworks/tree/mirador
