### ISSUE TITLE
Bookmarks overflow the document panel 

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/earthworks#1330]
When the screen is 994px wide, then the bookmark control overflows the document box. This is most apparent when the document is hovered over:

<img width="446" alt="Screenshot 2024-08-30 at 11 00 25 AM" src="https://github.com/user-attachments/assets/a2197d8a-dcc5-4b7e-a183-a83ab056e01c">

**Comment by dbranchini** [comment]
I didn't have a BS large version in the responsive designs earlier, but I just added one. I think at 992 px or a BS large breakpoint, we should collapse the map as we should be already for BS medium. See this design -- 

https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=1754-28838&t=yI2k5bo7xG7AKdAI-4

**Comment by dbranchini** [comment]
That gives us more space for the results, but if that's not doable, then I'd suggest replacing the Bookmark with just the icon, like the designs suggest for phone views - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=335-15305&t=yI2k5bo7xG7AKdAI-4. 

If that isn't a viable solution (since I noticed it doesn't do that now, then the Bookmark should appear below the title as it currently does.

**Comment by thatbudakguy** [comment]
It looks like this can't be replicated any longer, because:
- we now collapse the map below the large breakpoint
- on small screens, the bookmark shifts below the title
- on most screens smaller than large, users are using a touch device, so you can't hover to get the screenshot shown above
