### ISSUE TITLE
Link to record view on bookmarks page errors

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1383]
**Summary:** 
Links to the record view on the bookmarks page don't go to the record, and instead, the record title/link becomes the phrase "Content missing." 

**Steps to reproduce:**
1. Add a bookmark 
2. Go to bookmarks page
3. Click on a record title 

**What happens:**
The title/link changes to the phrase "Content missing"

**What should happen**
The link takes the user to the record view.

**Comment by thatbudakguy** [comment]
In local dev, this throws a `NoMethodError` for `dataset?` coming from:
https://github.com/sul-dlss/earthworks/blob/901e3c1ec5de3561b4c3cb92bfcd05ce2d5203d8/app/controllers/catalog_controller.rb#L334-L338

...which is weird, because `#dataset?` is definitely defined on our `SolrDocument`:
https://github.com/sul-dlss/earthworks/blob/901e3c1ec5de3561b4c3cb92bfcd05ce2d5203d8/app/models/solr_document.rb#L15-L17

**Comment by dnoneill** [comment]
This was happening before dataset? was added. This has to do with turbo being wrapped around the bookmark results in the _document_split file.
