### ISSUE TITLE
rightsMetadata disappears in Solr index

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#178]
Example: https://earthworks.stanford.edu/catalog/stanford-xy200cj2870.json

**Comment by drh-stanford** [comment]
Looked into this a little and I suspect that the stored but not indexed strategy for our rightsMetadata Solr field is not working with incremental updates. I'll re-publish with a different field.

**Comment by mejackreed** [comment]
Looks like all of the values have to be stored.  https://wiki.apache.org/solr/Atomic_Updates

"The core functionality of atomically updating a document requires that all fields in your SchemaXml must be configured as stored="true" except for fields which are <copyField/> destinations -- which must be configured as stored="false". This is because the atomic updates are applied to the document represented by the existing stored field values."

**Comment by drh-stanford** [comment]
I saw that documentation and the `stanford_rights_metadata_ss` is stored, but not indexed. I tested it and it worked so I'm a bit stumped right now. As far as I can see, the only thing updating the Solr index is GeoMonitor's atomic updates, and the `stanford_rights_metadata_ss` is the only field we store but not index.

So, I'm inclined to try renaming the field to `stanford_rights_metadata_s` so that it matches the other fields in the schema.
