### ISSUE TITLE
Users are ignoring licensing and distribution information

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#333]
Users are providing feedback to try and obtain licensed data from EarthWorks. This happens for both Stanford and other institution data. What can we do to make this more obvious to users.

**Comment by mapninja** [comment]
I put together a table of the institutions recently indexed and their contact info, where available (most) they are group emails:

[https://docs.google.com/spreadsheets/d/1w8iwWQoK_EwYMkW3MXftZs2-ZGGQIgMOesOn8JeOP4g/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1w8iwWQoK_EwYMkW3MXftZs2-ZGGQIgMOesOn8JeOP4g/edit?usp=sharing)

Here's some possible verbiage:

“This data is hosted by <Institution>, and is currently unavailable to preview and download. Stanford University does not hold this data and cannot provide access to it, at this time. If you have questions about this or other unavailable datasets from <Holding Institution dept> please submit your feedback to <holding institution group email>.”

**Comment by drh-stanford** [comment]
There are cases where a layer has no dct_references and thus isn't available for download or preview -- see https://kurma-earthworks-stage.stanford.edu/catalog/mit-002205609

But I'm a little confused from the language in the warning -- "If you have questions about this or other unavailable datasets please submit this as feedback " -- coz it's not really "currently unavailable", it's not downloadable because it's not online.

Maybe we can reword the "this or other unavailable datasets" to just "this or other datasets"?

**Comment by mapninja** [comment]
DO we need to unpack this a little more, even?
User / Status / Message
Stanford / Unavailable from Stanford / Provide feedback issue
Public / Unavailable from Stanford / Provide feedback issue
Public / Restricted from Stanford / Contact Publisher
Stanford / Restricted or Unavailable from other institution / Contact Librarian for Collection Dev
Public / Restricted or Unavailable from other institution / Contact Holding Institution

**Comment by drh-stanford** [comment]
Yeah, it does seem like we have a few use cases here. One wrench is that we don't know if they are a "Public" or "Stanford" user unless they login. So item 3 above might need to be "Login or Contact Publisher".

Right now, for item 3, we just have the following UI (no warning message):

![screen shot 2018-01-17 at 1 26 38 pm](https://user-images.githubusercontent.com/1861171/35067841-1eb0709c-fb8a-11e7-9ca5-3f5eaf68ee1c.png)
