### ISSUE TITLE
[earthworks/prod] ActionView::Template::Error: RSolr::Error::Http - 400 Bad Request
Error: {
  "responseHeader":{
    "zkConnected":true,
    "status":400,
    "QTime":4,
    "params":{
      "mm":"6<-1 6<90%",
      "qs":"1",
      "q.alt":"*:*",
      "facet.field":["dct_isPartOf_sm",
        "dct_provenance_s",

URI: https://sul-solr.stanford.edu/solr/kurma-earthworks-v1-prod/select?wt=json&fq=%7B%21join+from%3Ddc_source_sm+to%3Dlayer_slug_s%7Dlayer_slug_s%3Auva-Arlington%3ATract1990_Anno_14400&fl=dc_...

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/earthworks#437]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49895/faults/36313841)

**Comment by thatbudakguy** [comment]
This error was thrown by [a UVA record](https://github.com/OpenGeoMetadata/edu.virginia/blob/0f5c44780743edc11df98a43bffadb4d5bc4ee0a/360/71/geoblacklight.json#L8); their repository has since been deprecated since they moved off of geoblacklight. Closing since it can't be replicated anymore and the HB details are now lost to time.
