### ISSUE TITLE
Add citation support

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#594]
This is a commonly requested feature in GeoBlacklight so it would be great to add there.

**Comment by ggeisler** [comment]
The goal is something similar to what we do in Searchworks?

<img width="944" alt="Screen Shot 2020-05-22 at 12 33 56 PM" src="https://user-images.githubusercontent.com/101482/82707481-ff12b200-9c30-11ea-8291-3a16311321a8.png">

**Comment by mejackreed** [comment]
I'm not sure we have to do all of the different formats. Just one would likely be enough. We are also working with these metadata pretty consistently.

https://earthworks.stanford.edu/catalog/stanford-gd672hm7648/raw

**Comment by ggeisler** [comment]
I wonder if geo-related journals tend to use one or more citations formats, which might help us decide which format(s) to support?

Some fields tend towards certain formats (e.g. MLA and Chicago in the humanities) but I don't know much off-hand about geo-related journals. I could look into it, though, and recommend which format(s) we might support.

And then I guess I should get a better understanding what metadata (e.g., from all the fields in the linked example above) is typically included in geo-oriented citations.

Anyway, I think I understand the goal so just need to look into the details of what and how we present the actual citations.

**Comment by mejackreed** [comment]
I'm not sure about that. One real world use case we can provide. We received this feedback from a researcher (not at Stanford).

>  What is the proper way to cite these data? We will be using them in maps created for an official U.S. gov't publication and want to ensure proper attribution. Thanks

**Comment by kimdurante** [comment]
We auto-generate a citation for EarthWorks layers using the same format as Hydrus (unless otherwise specified). It is available in the MODS metadata for each object.
https://purl.stanford.edu/mc977kq8162

(note displayLabel="Preferred citation")

**Comment by ggeisler** [comment]
> What is the proper way to cite these data? We will be using them in maps created for an official U.S. gov't publication and want to ensure proper attribution. Thanks

My point was that there is no definitive answer to a question like this. There are a handful of established citation style guides (APA, Chicago, MLA, etc.) and they differ in their rules for forming a citation. Knowing which one to use usually depends on the publication venue in which you are going to be citing a work. Different publication venues require you to follow different citation styles. That's why Searchworks offers a handful of choices; you can copy the one that fits the publication in which you intend to cite the work.

From a little bit of investigation it seems like the style guides don't always have a clearly stated citation style for geospatial works, perhaps because there are so many varieties of geospatial works. 

I'll spend a little more time looking into this but given the variety and complexity of geospatial works, maybe our solution is just to use the "Preferred citation" approach @kimdurante pointed out. That would serve as a good general purpose citation and if the user is publishing in a venue that requires a different style, they can modify that general purpose citation as necessary.

So the work for this ticket might involve:
- Determine what kind of UI affordance we should use to display the citation for a given work (a button that displays a modal with the citation; showing the citation directly in the page somewhere; etc.)
- Making sure we know how to construct the citation for all the varieties of works in Earthworks

**Comment by mejackreed** [comment]
I think this is a good approach. One complexity is that we will need to build the citation from GeoBlacklight-Schema metadata rather than mods since we are dealing with data that is not just Stanford's. By using GeoBlacklight-Schema we can also contribute this feature back to core GeoBlacklight.

**Comment by ggeisler** [comment]
@mejackreed Unfortunately, building the citation from the GeoBlacklight-Schema metadata looks like it is going to be challenging, if the goal is to use a single method that works for all institutions. 

For example, the Stanford metadata is pretty consistent and we can create a citation that basically matches what we currently do in PURL's "Preferred citation" by using these GeoBlacklight-Schema fields:

- dc_creator_sm
- dct_issued_s
- dc_title_s
- dc_identifier_s

Using those fields, we can create citations like:

> California. Metropolitan Transportation Commission. (2002). HOV Lanes, San Francisco Bay Area, 2002. MTC. Available at: http://purl.stanford.edu/mc977kq8162.

> National Geophysical Data Center, United States. Department of Commerce,
United States. National Oceanic and Atmospheric Administration. (1999). 90-Meter Bathymetric Grid, New England, 1999. Available at: http://purl.stanford.edu/hq880bh1533.

> United States. Department of Housing and Urban Development. (2016). ACS 5 Year Housing Data by State, 2008-2012. Available at: http://purl.stanford.edu/jv400qp1099.

But other institutions vary widely in whether and how they use those fields. Here are some random examples:

### Princeton
https://earthworks.stanford.edu/catalog/princeton-n009w382v

*No dct_issued_s value; no dc_identifier_s*

> Sanborn Map Company. Princeton, Mercer County, New Jersey (Sheet 1).


### MIT
https://earthworks.stanford.edu/catalog/mit-001145244

*Only has title value*

> 1:1 500 000 series [cartographic material] : tectonic map of Britain, Ireland and adjacent areas / British Geological Survey ; Geological Survey of Ireland ; Geological Survey of Northern Ireland.

### NYU
https://earthworks.stanford.edu/catalog/nyu-2451-34620

*Missing author/creator*

> (1797). 1797 Plan of the City of Dublin, Ireland. Available at: http://hdl.handle.net/2451/34620.

### Columbia
https://earthworks.stanford.edu/catalog/sde-columbia-mapofbaltimore1920

*Empty dct_issued_s value; dc_identifier_s not a followable URL*

> Digital Social Science Center (DSSC), Columbia University Libraries. A Map of Baltimore, 1920.

---

Given the above, I can think of a couple of ways to proceed:

- Add the citation feature to Earthworks only, and leave it up to other GeoBlacklights to implement their own version if and when they want to. Even if we stick to the GeoBlacklight-Schema, our metadata looks consistent enough to produce reliable, if basic, citations. (Though if we do focus on just Stanford citations, then I wonder if we should use our MODS fields instead?)

- Add the citation feature to GeoBlacklight, but create multiple, institution-specific methods to create the best possible citation for each institution, given their GeoBlacklight-Schema metadata (but: a fair amount of analysis will be required (e.g., analyze each institution's metadata to find the best fields to use for them); maybe we shouldn't decide on the citation approach for other institutions; for some institutions, the metadata might not be good enough to reliably display a useful citation even with an institution-specific method).

- Add the citation feature to GeoBlacklight with a single method as in my examples above, and just live with the fact that there will be a lot of inconsistency and incompleteness among records from different institutions.

I think the first option is best, but I don't know if there are GeoBlacklight community considerations that might make pursuing one of the other options more important, even if the result will be less than ideal.

**Comment by mejackreed** [comment]
I'm inclined to try to go with option 3. The reasons. Having limited citations will hopefully push the community in producing better metadata, or metadata tooling which would could solve some of these issues for everyone. The Columbia and MIT data we have are quite stale so maybe there is an opportunity to enhance that in other pieces of work. Additionally we may want to add functionality where if a external reference is not provided, fallback to the application url for citation.

**Comment by ggeisler** [comment]
Okay, thanks @mejackreed. That sounds reasonable. I'll finish this up with details for a recommendation for pursuing the third approach.

**Comment by ggeisler** [comment]
There are two main parts to this: 1) adding an affordance to display a citation for an item, and 2) generating the citation to display.

## Add a citation UI affordance
I suggest adding a "Cite" link to the existing Tools sidebar box:

<img width="257" alt="Screen Shot 2020-06-16 at 10 00 53 AM" src="https://user-images.githubusercontent.com/101482/85333549-a122f580-b48e-11ea-8a50-7aba24db84a2.png">

- Icon: `fa-quote-left`: https://fontawesome.com/icons/quote-left?style=solid

- Label: "Cite"

- Location: I suggest putting it directly after the bookmark action, because I'm guessing copying the citation might be a more frequent user need than the other Tools actions. But if this technically difficult because we're inheriting the Tools box with the bookmark and email actions from Blacklight or something, it could go after Email (but it does feel like it should go before Web services, Metadata, and Open in Carto).

- Action: When the user selects the Cite action, display a modal with the title "Preferred citation":

<img width="1143" alt="Screen Shot 2020-06-22 at 3 21 52 PM" src="https://user-images.githubusercontent.com/101482/85341074-2b258b00-b49c-11ea-9ce1-fea692b8aa9d.png">


## Generate citation from GeoBlacklight schema metadata
Use these GeoBlacklight schema metadata fields to form the citation:

- dc_creator_sm
- dct_issued_s
- dc_title_s
- dc_format_s
- dc_publisher_s

In addition, add a "Retrieved from " string followed by the URL of the current show page.

Putting those together with the necessary punctuation should look generically like this:

> Creator. (Issued date). Title [format]. Publisher. Retrieved from https://earthworks.stanford.edu/catalog/item_identifier

A few things make this a bit more complicated and confusing than ideal:

- The GeoBlacklight schema metadata for items from institutions other than Stanford are often missing one or more of the fields used to create the citation.

- Unlike more standard book or journal records, a lot of the geo records include the same value for creator and publisher; this isn't a problem for following the template to generate the citation, it can just be a bit visually confusing.

- The issued date is often different than the year the item is about, and the latter is often in the title, so you get a lot of records with different years in the citation. Again, not a problem for generating the citation, just visually confusing.

Below are a handful of examples I created when analyzing this issue, which might be helpful for testing or verifying the code used to generate the citation matches the goal.

### Stanford examples
https://earthworks.stanford.edu/catalog/stanford-hq880bh1533/raw

**dc_creator_sm:** National Geophysical Data Center
United States. Department of Commerce
United States. National Oceanic and Atmospheric Administration
United States. National Environmental Satellite, Data, and Information Service
**dct_issued_s:** 1999
**dc_title_s:** 90-Meter Bathymetric Grid, New England, 1999
**dc_format_s:** ArcGRID
**dc_publisher_s**: National Geophysical Data Center

> National Geophysical Data Center, United States. Department of Commerce,
United States. National Oceanic and Atmospheric Administration. (1999). 90-Meter Bathymetric Grid, New England, 1999 [ArcGRID]. National Geophysical Data Center. Retrieved from https://earthworks.stanford.edu/catalog/stanford-hq880bh1533

---

https://earthworks.stanford.edu/catalog/stanford-sv613mt4586/raw

> East View Cartographic, Inc. Instituto Nacional de Estadística (Honduras). (2018). 10 Year Age Groups, Honduras, 2013 [Shapefile]. Retrieved from https://earthworks.stanford.edu/catalog/stanford-sv613mt4586

--- 

https://earthworks.stanford.edu/catalog/stanford-qb865wf0229/raw

> Air Flight Services. (2019). Stanford Campus 2010, Index Map [Shapefile]. Stanford Digital Repository. Retrieved from https://earthworks.stanford.edu/catalog/stanford-qb865wf0229

### Other institution examples

#### Harvard (missing creator and issued fields)

https://earthworks.stanford.edu/catalog/harvard-glb-co-usa/raw

**dc_creator_sm:** *not present*
**dct_issued_s:** *not present*
**dc_title_s:** 2000 county boundaries of the United States
**dc_format_s:** Shapefile
**dc_publisher_s:** U.S. Geological Survey

> 2000 county boundaries of the United States [Shapefile]. U.S. Geological Survey. Retrieved from https://earthworks.stanford.edu/catalog/harvard-glb-co-usa

#### Princeton (missing issued field)

https://earthworks.stanford.edu/catalog/princeton-n009w382v/raw

Sanborn Map Company. Princeton, Mercer County, New Jersey (Sheet 1) [TIFF]. New York : Sanborn Map & Publishing Co., Limited, 1885. Retrieved from https://earthworks.stanford.edu/catalog/princeton-n009w382v

#### MIT (missing creator and issued fields) 
https://earthworks.stanford.edu/catalog/mit-001145244/raw

> 1:1 500 000 series [cartographic material] : tectonic map of Britain, Ireland and adjacent areas / British Geological Survey ; Geological Survey of Ireland ; Geological Survey of Northern Ireland [GeoTIFF]. British Geological Survey. Retrieved from https://earthworks.stanford.edu/catalog/mit-001145244

#### NYU (missing creator and publisher fields)

https://earthworks.stanford.edu/catalog/nyu-2451-34620/raw

> (1797). 1797 Plan of the City of Dublin, Ireland [GeoTIFF]. Retrieved from https://earthworks.stanford.edu/catalog/nyu-2451-34620

#### Columbia (issued field is present but value is empty)

https://earthworks.stanford.edu/catalog/sde-columbia-mapofbaltimore1920

> Digital Social Science Center (DSSC), Columbia University Libraries. A Map of Baltimore, 1920 [GeoTIFF]. A. Hoen & Co. Retrieved from https://earthworks.stanford.edu/catalog/sde-columbia-mapofbaltimore1920

**Comment by mejackreed** [comment]
Resolved upstream in GeoBlacklight, will be updated in EarthWorks during dependency update.
