### ISSUE TITLE
Migrate Universal Analytics (UA) to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by corylown** [sul-dlss/earthworks#914]
Universal Analytics (UA) properties will [stop collecting data as of July 1, 2023](https://support.google.com/analytics/answer/11583528?hl=en). The data in the existing UA property will remain available for an unspecified period of time. In order to collect data after July 1, 2023 we will need to create a new GA4 property and add the newer `gtag.js` snippet to the application in order to collect data into the new GA4 property.

Spreadsheet that tracks properties and whether each property is tracking events: https://docs.google.com/spreadsheets/d/1WWt3l-RFqfb_L2j01Y7JBUWJ2OnX0Hi4xLmIW8abNLw/edit?usp=sharing

- [x] [Add a Google Analytics 4 property](https://support.google.com/analytics/answer/9744165#zippy=%2Cin-this-article)
- [x] [Add the Google tag to the application](https://support.google.com/analytics/answer/9304153#zippy=%2Cadd-your-tag-using-google-tag-manager%2Cadd-the-google-tag-directly-to-your-web-pages)
- [x] [Set up event tracking as desired](https://support.google.com/analytics/answer/11091025#zippy=%2Cin-this-article). NOTE: _everything_ is an event in GA4 and it automatically collects some events.
- [ ] Set up debug_mode filter (https://support.google.com/analytics/answer/13296662?hl=en)
- [ ] Optionally, download and archive the historical UA data.

NOTE: There is currently a [setting available](https://support.google.com/analytics/answer/11150547) that will send events from `analytics.js` (UA) to GA4 properties. However, Google does not guarantee this will continue to work after July 1, 2023. This is not recommended as a migration path for event tracking.

**Comment by thatbudakguy** [comment]
Earthworks tracks these custom events:
https://github.com/sul-dlss/earthworks/blob/687ae5794e2c929c72596d7631a8e37082e9f143/app/assets/javascripts/modules/analytics.js#L55-L83

Of these:
* "Map moved" relies on reading changes to the history API, but this isn't accurate because Turbo also manipulates this API during non-"map move" events (regular searches). Unclear if anyone was paying attention to this, but it's likely been wrong for some time.
* "Search here" clicks are automatically tracked as form submissions using enhanced event tracking.
* "Download" clicks are automatically tracked as file downloads using enhanced event tracking.
* It's unclear why we would want to track failed downloads, but this might be able to be gleaned from data under file download events.
* "Open in CartoDB" is going away: #848 

#961 removes the bespoke analytics code entirely. If we decide we're missing some crucial data, we can look at implementing custom events for it.
